### ISSUE TITLE
Replace Exercise 6.1.3

### ISSUE THREAD

**Issue by squell** [tweedegolf/rust-training#121]
We can find some C code that is more easy to understand and also a little bit more "interesting" to Rust people than crypto code from this rather "special" crypto library.

**Comment by tdittr** [comment]
Lets use QOI the quite ok image format, if you call it with a bad buffer the output should look clearly wrong :D https://qoiformat.org/

**Comment by tdittr** [comment]
Yeah, it is a header only library. A lot of C/C++ libraries do that by now to make dependency management easier...
