### ISSUE TITLE
Make GitHub pages render on training.tweede.golf instead of tweedegolf.github.io/rust-training

### ISSUE THREAD

**Issue by hugovandepol** [tweedegolf/rust-training#43]

**Comment by squell** [comment]
Duplicate of #29, which is fixed already in the repo (but not yet deployed to the old website since we're in the process of removing that).

See: https://tweedegolf.github.io/rust-training/

We should update the link in the README though.

**Comment by squell** [comment]
And also, make https://training.tweede.golf  forward to https://tweedegolf.github.io/rust-training/

**Comment by squell** [comment]
That's now done!
